# Generated by Django 4.0.4 on 2022-05-23 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classPackages', '0010_remove_hours_am_remove_hours_pm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription', '0009_alter_subscription_begin_date_and_more'),
        ('posts', '0008_alter_postproductid_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.IntegerField()),
                ('is_payment', models.BooleanField()),
                ('is_purchase', models.BooleanField()),
                ('is_refund', models.BooleanField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('classPackage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classPackages.publicpackage')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.post')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
