# Generated by Django 4.0.4 on 2022-05-28 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userTransactions', '0003_remove_creator_balance_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='creator_balance',
        ),
    ]
