# Generated by Django 4.0.3 on 2022-04-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_comment_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
