# Generated by Django 4.0.4 on 2022-04-29 03:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_postproductid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postproductid',
            name='id',
        ),
        migrations.AlterField(
            model_name='postproductid',
            name='post',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='posts.post'),
            preserve_default=False,
        ),
    ]
