# Generated by Django 4.0.4 on 2022-04-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_postproductid_id_alter_postproductid_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postproductid',
            name='st_priceId',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='postproductid',
            name='st_productId',
            field=models.CharField(max_length=500),
        ),
    ]
