# Generated by Django 4.0.4 on 2022-10-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_delete_tags'),
        ('posts', '0009_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.tag'),
        ),
    ]
