# Generated by Django 4.0.2 on 2022-02-28 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_custom_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_profile',
            name='pic',
            field=models.ImageField(blank=True, upload_to='profile-pictures/'),
        ),
    ]
