# Generated by Django 4.0.2 on 2022-03-05 16:39

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_custom_profile_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='custom_profile',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
