# Generated by Django 4.0.2 on 2022-03-09 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_custom_profile_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='custom_profile',
            managers=[
            ],
        ),
    ]
