# Generated by Django 4.0.2 on 2022-03-09 19:16

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_custom_profile_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='custom_profile',
            managers=[
                ('objects', users.models.profile_manager()),
            ],
        ),
    ]
