# Generated by Django 4.0.4 on 2022-04-30 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_customerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerid',
            name='customerId',
            field=models.CharField(max_length=500),
        ),
    ]
