# Generated by Django 4.0.4 on 2022-05-28 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_creator_balance_custom_profile_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creator_balance',
            old_name='balance',
            new_name='units',
        ),
    ]
