# Generated by Django 4.0.4 on 2022-05-05 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classPackages', '0003_rename_duration_units_publicpackage_duration'),
        ('posts', '0008_alter_postproductid_post'),
        ('subscription', '0007_subscription_st_subid_alter_subscription_begin_date_and_more'),
        ('siteTally', '0002_alter_sitetransaction_st_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitetransaction',
            name='classPackage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classPackages.publicpackage'),
        ),
        migrations.AlterField(
            model_name='sitetransaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sitetransaction',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.post'),
        ),
        migrations.AlterField(
            model_name='sitetransaction',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.subscription'),
        ),
    ]
