# Generated by Django 4.0.4 on 2022-05-29 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_alter_verification_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='verificationStatus',
        ),
        migrations.AlterField(
            model_name='verification',
            name='reason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
