# Generated by Django 4.0.4 on 2022-05-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classPackages', '0004_days_hours_package_days_publicpackage_days_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package_days',
            name='tuesday',
            field=models.BooleanField(verbose_name='tuesday'),
        ),
    ]
