# Generated by Django 4.0.4 on 2022-05-09 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classPackages', '0006_alter_package_days_friday_alter_package_days_monday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicpackage',
            name='days_available',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classPackages.package_days'),
        ),
    ]
