# Generated by Django 4.0.4 on 2022-05-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classPackages', '0007_alter_publicpackage_days_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='months',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthStr', models.CharField(max_length=50)),
                ('monthInt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='years',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='hours',
            name='am',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hours',
            name='pm',
            field=models.BooleanField(default=False),
        ),
    ]
