# Generated by Django 4.0.4 on 2022-05-14 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classPackages', '0009_dayint_rename_months_month_rename_years_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hours',
            name='am',
        ),
        migrations.RemoveField(
            model_name='hours',
            name='pm',
        ),
    ]
