# Generated by Django 4.0.4 on 2022-06-01 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('verification passed', 'Verification Passed'), ('verification failed', 'Verification Failed'), ('purchase refund', 'Purchase Refund'), ('subscription purchase', 'Subscription Purchase'), ('class purchase', 'Class Purchase'), ('post purchase', 'Post Purchase'), ('post like', 'Post Like'), ('post comment', 'Post Comment'), ('follw', 'Follow')], max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('seen', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
