# Generated by Django 4.0.4 on 2022-06-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userNotifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_notification',
            name='type',
            field=models.CharField(choices=[('passed verification', 'Verification Passed'), ('failed verification', 'Verification Failed'), ('refund', 'Purchase Refund'), ('purchase subscription', 'Subscription Purchase'), ('purchase class', 'Class Purchase'), ('purchase post', 'Post Purchase'), ('like post', 'Post Like'), ('comment post', 'Post Comment'), ('follow', 'Follow')], max_length=100),
        ),
    ]
