# Generated by Django 4.0.3 on 2022-04-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_options_thread_has_unread'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-last_viewed']},
        ),
        migrations.AddField(
            model_name='message',
            name='answered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_call',
            field=models.BooleanField(default=False),
        ),
    ]
