# Generated by Django 4.0.4 on 2022-05-11 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_appointment_date_remove_appointment_package_and_more'),
        ('classPackages', '0009_dayint_rename_months_month_rename_years_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsessionid',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classPackages.dayint'),
        ),
        migrations.AddField(
            model_name='classsessionid',
            name='hours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classPackages.hours'),
        ),
        migrations.AddField(
            model_name='classsessionid',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classPackages.month'),
        ),
        migrations.AddField(
            model_name='classsessionid',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classPackages.year'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='packageSessionId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.classsessionid'),
        ),
    ]
