# Generated by Django 4.0.4 on 2022-05-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_classsessionid_day_classsessionid_hours_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classsessionid',
            old_name='hours',
            new_name='start',
        ),
        migrations.RemoveField(
            model_name='classsessionid',
            name='day',
        ),
        migrations.RemoveField(
            model_name='classsessionid',
            name='month',
        ),
        migrations.RemoveField(
            model_name='classsessionid',
            name='year',
        ),
        migrations.AddField(
            model_name='classsessionid',
            name='date',
            field=models.CharField(default='12233', max_length=100),
            preserve_default=False,
        ),
    ]
