# Generated by Django 4.0.4 on 2022-05-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_rename_hours_classsessionid_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_insctructor',
            field=models.BooleanField(default=False),
        ),
    ]
