# Generated by Django 4.0.4 on 2022-05-12 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_appointment_is_insctructor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='is_insctructor',
            new_name='is_instructor',
        ),
    ]
