# Generated by Django 4.0.4 on 2022-05-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_rename_is_insctructor_appointment_is_instructor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classsessionid',
            old_name='date',
            new_name='end_time',
        ),
        migrations.RemoveField(
            model_name='classsessionid',
            name='start',
        ),
        migrations.AddField(
            model_name='classsessionid',
            name='start_time',
            field=models.CharField(default='heller', max_length=100),
            preserve_default=False,
        ),
    ]
