# Generated by Django 4.0.4 on 2022-10-27 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_alter_tags_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tags',
        ),
    ]
