# Generated by Django 4.0.3 on 2022-04-28 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='auto_draft',
            field=models.BooleanField(default=False),
        ),
    ]
