# Generated by Django 4.0.4 on 2022-04-30 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_subscriptionproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscription_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_productId', models.CharField(max_length=500)),
                ('st_priceId', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='subscriptionProduct',
        ),
    ]
