# Generated by Django 4.0.4 on 2022-05-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_subscription_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='st_subId',
            field=models.CharField(default='nope', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='begin_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.CharField(max_length=50),
        ),
    ]
