# Generated by Django 4.0.4 on 2022-04-30 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_postproductid_st_priceid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postproductid',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='productID', serialize=False, to='posts.post'),
        ),
    ]
