# Generated by Django 4.0.4 on 2022-05-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_postproductid_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
