# Generated by Django 4.0.4 on 2022-05-11 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classPackages', '0008_months_years_alter_hours_am_alter_hours_pm'),
        ('booking', '0002_rename_purchaser_appointment_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='package',
        ),
        migrations.AddField(
            model_name='appointment',
            name='logged_on',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='classSessionId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_logged_on', models.BooleanField(default=False)),
                ('classPackage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classPackages.publicpackage')),
            ],
        ),
    ]
