# Generated by Django 4.0.3 on 2022-04-27 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classPackages', '0003_rename_duration_units_publicpackage_duration'),
        ('subscription', '0001_initial'),
        ('posts', '0004_alter_post_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('units', models.IntegerField()),
                ('is_payment', models.BooleanField()),
                ('is_refund', models.BooleanField()),
                ('classPackage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classPackages.publicpackage')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.post')),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
