# Generated by Django 4.0.4 on 2022-05-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userTransactions', '0002_alter_usertransactionitem_classpackage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertransactionitem',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
