# Generated by Django 4.0.4 on 2022-05-28 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userTransactions', '0002_creator_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator_balance',
            name='user',
        ),
    ]
