# Generated by Django 4.0.2 on 2022-03-03 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_custom_profile_pic'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='custom_profile',
            managers=[
            ],
        ),
    ]
