# Generated by Django 4.0.2 on 2022-03-09 23:53

import django.contrib.auth.models
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_custom_profile_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='custom_profile',
            managers=[
                ('search', users.models.profile_manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='custom_profile',
            name='subscription_units',
            field=models.IntegerField(default=0),
        ),
    ]
