# Generated by Django 4.0.3 on 2022-03-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_custom_profile_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_profile',
            name='banner',
            field=models.ImageField(blank=True, upload_to='profile-banners/'),
        ),
    ]
