# Generated by Django 4.0.4 on 2022-04-30 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_subscription_product_delete_subscriptionproduct'),
        ('users', '0014_alter_customerid_customerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_profile',
            name='subscription_product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscription.subscription_product'),
        ),
    ]
