# Generated by Django 4.0.4 on 2022-04-30 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_alter_subscription_auto_draft'),
        ('users', '0015_custom_profile_subscription_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_profile',
            name='subscription_product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscription.subscription_product'),
        ),
    ]
