# Generated by Django 4.0.4 on 2022-04-30 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_custom_profile_subscription_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_profile',
            name='subscription_product',
        ),
    ]
