# Generated by Django 4.0.4 on 2022-10-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_delete_tags'),
        ('users', '0020_alter_custom_profile_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_profile',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.tag'),
        ),
    ]
