# Generated by Django 4.0.3 on 2022-03-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classPackages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicpackage',
            name='duration_units',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='publicpackage',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
