# Generated by Django 4.0.3 on 2022-03-23 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classPackages', '0002_publicpackage_duration_units_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicpackage',
            old_name='duration_units',
            new_name='duration',
        ),
    ]
