# Generated by Django 4.0.4 on 2022-05-08 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classPackages', '0003_rename_duration_units_publicpackage_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField()),
                ('am', models.BooleanField()),
                ('pm', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='package_days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.BooleanField()),
                ('tuesday', models.BooleanField()),
                ('wednesday', models.BooleanField()),
                ('thursday', models.BooleanField()),
                ('friday', models.BooleanField()),
                ('saturday', models.BooleanField()),
                ('sunday', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='publicpackage',
            name='days_available',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classPackages.package_days'),
        ),
        migrations.AddField(
            model_name='publicpackage',
            name='from_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='earliest', to='classPackages.hours'),
        ),
        migrations.AddField(
            model_name='publicpackage',
            name='to_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='latest', to='classPackages.hours'),
        ),
    ]
