# Generated by Django 4.0.4 on 2022-05-09 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classPackages', '0005_alter_package_days_tuesday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package_days',
            name='friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='package_days',
            name='monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='package_days',
            name='saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='package_days',
            name='sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='package_days',
            name='thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='package_days',
            name='tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='package_days',
            name='wednesday',
            field=models.BooleanField(default=False),
        ),
    ]
