# Generated by Django 4.0.4 on 2022-05-11 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_appointment_date_remove_appointment_package_and_more'),
        ('classPackages', '0008_months_years_alter_hours_am_alter_hours_pm'),
    ]

    operations = [
        migrations.CreateModel(
            name='dayInt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='months',
            new_name='month',
        ),
        migrations.RenameModel(
            old_name='years',
            new_name='year',
        ),
        migrations.AddField(
            model_name='publicpackage',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='publicPackageProductId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_productId', models.CharField(max_length=300)),
                ('st_priceId', models.CharField(max_length=300)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classPackages.publicpackage')),
            ],
        ),
    ]
